name: klyp_dev_test

networks:
  internal:
    external: false

services:
  # nginx
  klyp_dev_test_web:
    container_name: klyp_dev_test_web
    build: 
      context: ./images/nginx
    restart: 'no'
    depends_on:
      - klyp_dev_test_mongodb
    volumes: 
      - ../www:/var/www

      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/other.conf.d:/etc/nginx/other.conf.d

      - ./logs/nginx:/var/log/nginx/
    environment: 
      - TZ=Australia/Perth
    ports:
      - "127.0.0.1:8089:80"
    networks:
      - internal

  # php
  klyp_dev_test_php:
    container_name: klyp_dev_test_php
    build: 
      context: ./images/php
    restart: 'no'
    depends_on:
      - klyp_dev_test_mongodb
    volumes:
      - ../www:/var/www

      - ./config/php/php.development.ini:/usr/local/etc/php/php.ini
      - ./config/fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./config/fpm/php-fpm.d:/usr/local/etc/php-fpm.d

      - ./logs/fpm/php:/var/log/fpm
    environment: 
      - TZ=Australia/Perth
    networks:
      - internal
  
  # php_8080
  klyp_dev_test_php_8080:
    container_name: klyp_dev_test_php_8080
    build: 
      context: ./images/php
    restart: 'no'
    depends_on:
      - klyp_dev_test_mongodb
    volumes:
      - ../www:/var/www

      - ./config/php/php.development.ini:/usr/local/etc/php/php.ini
      - ./config/fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./config/fpm/php-fpm.d:/usr/local/etc/php-fpm.d

      - ./logs/fpm/php:/var/log/fpm
    environment: 
      - TZ=Australia/Perth
    networks:
      - internal
 
  # pgsql
  klyp_dev_test_mongodb:
    container_name: klyp_dev_test_mongodb
    build: 
      context: ./images/mongodb
    restart: 'no'
    volumes: 
      - ./data/mongodb:/data/db
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
    command: mongod
    environment: 
      - TZ=Australia/Perth

      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      # - MONGO_INITDB_DATABASE=klyp_dev_test
    networks:
      - internal
  
